#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.html
sudo printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    index  index.html index.htm;
    root   /var/www/html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx restart
