#!/usr/bin/env bash
# Configure HAProxy load balancer server

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee --append  /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 29305-web-01 3.229.124.209:80 check
    server 29305-web-02 3.236.114.249:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
